---
app:
  default-request-timeout: 60000
  persistence:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      username: app
      password: sqlpass
      url: jdbc:mariadb://127.0.0.1:3307/federation?ssl=false&createDatabaseIfNotExist=true
    jpa:
      dialect: org.hibernate.dialect.MariaDB53Dialect
      generate-ddl: true
      ddl-auto: create
      show-sql: true
      format_sql: true
      use_sql_comments: true
      properties:
        hibernate.temp.use_jdbc_metadata_defaults: false
  # Solr
  solr:
    enabled: false
    base-url: http://localhost:8983/solr
    collection-name: app


  # CORS
  cors:
    enabled: true
    allowedOrigin: '*'
    allowedMethods: GET,POST,PUT,DELETE
    allowedHeaders:
      - Authorization
      - X-Requested-With
      - Content-Type
    maxAge: 3600

  # Cache configuration
  cache:
    embedded:
      enabled: true

  # Swagger
  swagger:
    enabled: true

  # OAuth
  oauth:
    authentication:
      type: DB
      ldap:
        user-dn-patterns:
          - sn={0},ou=People
          - sn={0},ou=People2
        group-search-base: ou=Group
        group-search-filter: member={0}
        context-source-url: ldap://192.168.1.219:389/dc=izertis,dc=com
    authorization-server:
      enabled: true
      client-type: INMEMORY
      client-id: acme
      client-secret: acmesecret
      token-store-type: INMEMORY
    resource-server:
      enabled: true
      type: EMBED
    unprotected-url:
      - /**
      - /public/**
      - /oauth/**
      - /management/**

## Actuator
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /management
  server:
    port: 9328
  health:
    mail:
      enabled: false
    ldap:
      enabled: false
    redis:
      enabled: false
    solr:
      enabled: ${app.solr.enabled}

## In case of configure web endpoints, remove it or change port number
server:
  port: ${management.server.port}

data-sources:
  nodes:
    - nodeName: um
      services:
        - name: sparql-proxy
          baseUri: http://herc-iz-front-desa.atica.um.es
          port: 8080
          user:
          password:
          types:
            - name: sparql
              suffixURL: /trellis/sparql
              user:
              password:
        - name: uris-factory
          baseUri: http://localhost
          port: 9326
          user:
          password:
        - name: trellis
          baseUri: http://herc-iz-front-desa.atica.um.es
          port:
          user: admin
          password: admin
    - nodeName: um2
      services:
        - name: sparql-proxy
          baseUri: http://herc-iz-front-desa.atica.um.es
          port: 8080
          user:
          password:
          types:
            - name: trellis
              suffixURL: /trellis/sparql
              user:
              password:
        - name: uris-factory
          baseUri: http://localhost
          port: 8080
          user:
          password:
        - name: trellis
          baseUri: http://herc-iz-front-desa.atica.um.es
          port:
          user: admin
          password: admin
data-sets:
  - name: SCOPUS
    connection:
      - type: api
        baseURL: https://api.elsevier.com/content/
        apiKey: 9c16500dca380fb18aa8014ecc812ad9
        mappings:
          classes:
            - localName: Universidad
              remoteName:

