INSERT INTO APPLICATION_USER 
	(ID, ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED, ADDRESS, CITY, COUNTRY, CREDENTIALS_NON_EXPIRED, EMAIL, ENABLED, LANGUAGE, NAME, PASSWORD, PASSWORD_RECOVERY_HASH, USERNAME, VERSION) 
VALUES 
	('1', true, true, '1', '1', '1', true, 'b@t.com', true, '1', 'user', '{bcrypt}$2a$10$08d0l3aRNN.DQ/CgHFmZNOUmpaWSjWsTRzN/Dcd.1WEhpQ13CEDxK', 'secret', 'user', 1);

INSERT INTO application_user_role (ROLE, USER_ID) VALUES ('ADMINISTRATOR', '1');