---
app:
  host: http://localhost
  port: 9328
  node: um
  name: Federation
  healthEndpoint: /management/health
  tripleStores: fuseki
  service-discovery-host: http://localhost:9329
  trellis-host: http://localhost
  default-request-timeout: 60000
  persistence:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      username: app
      password: sqlpass
      url: jdbc:mariadb://127.0.0.1:3307/federation?ssl=false&createDatabaseIfNotExist=true
    jpa:
      dialect: org.hibernate.dialect.MariaDB53Dialect
      generate-ddl: true
      ddl-auto: create
      show-sql: true
      format_sql: true
      use_sql_comments: true
      properties:
        hibernate.temp.use_jdbc_metadata_defaults: false
  # Solr
  solr:
    enabled: false
    base-url: http://localhost:8983/solr
    collection-name: app


  # CORS
  cors:
    enabled: true
    allowedOrigin: '*'
    allowedMethods: GET,POST,PUT,DELETE
    allowedHeaders:
      - Authorization
      - X-Requested-With
      - Content-Type
    maxAge: 3600

  # Cache configuration
  cache:
    embedded:
      enabled: true

  # Swagger
  swagger:
    enabled: true

  # OAuth
  oauth:
    authentication:
      type: DB
      ldap:
        user-dn-patterns:
          - sn={0},ou=People
          - sn={0},ou=People2
        group-search-base: ou=Group
        group-search-filter: member={0}
        context-source-url: ldap://192.168.1.219:389/dc=izertis,dc=com
    authorization-server:
      enabled: true
      client-type: INMEMORY
      client-id: acme
      client-secret: acmesecret
      token-store-type: INMEMORY
    resource-server:
      enabled: true
      type: EMBED
    unprotected-url:
      - /**
      - /public/**
      - /oauth/**
      - /management/**

## Actuator
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /management
  server:
    port: ${app.port}
  health:
    mail:
      enabled: false
    ldap:
      enabled: false
    redis:
      enabled: false
    solr:
      enabled: ${app.solr.enabled}

## In case of configure web endpoints, remove it or change port number
server:
  port: ${management.server.port}

endpoint:
  nodeName: um
  connectors:
    - type: fuseki
      host: http://localhost
      port: 3030
      suffixURL: /trellis/query
      queryParamName: query


lod-data-sources:
  datasets:
    - name: SCOPUS
      connections:
        - connectionType: API
          def: true
          baseURL: https://api.elsevier.com/content/
          apiKey: 9c16500dca380fb18aa8014ecc812ad9
          mappings:
            - remoteName: SCOPUS
              remoteAttribute: DOI
              suffixURL: search/scopus
              identifier: true
              order: 1
              localClasses:
                - name: Article
                  attributes:
                    - doi
                  mappers:
                    - remoteAttribute: "prism:doi"
                      localAttribute: "doi"
                    - remoteAttribute: "dc:title"
                      localAttribute: "title"
                - name: Book
                  attributes:
                    - doi
                  mappers:
                    - remoteAttribute: "prism:doi"
                      localAttribute: "doi"
                    - remoteAttribute: "dc:title"
                      localAttribute: "title"
                - name: BookChapter
                  attributes:
                    - doi
                  mappers:
                    - remoteAttribute: "prism:doi"
                      localAttribute: "doi"
                    - remoteAttribute: "dc:title"
                      localAttribute: "title"
                - name: BookSection
                  attributes:
                    - doi
                  mappers:
                    - remoteAttribute: "prism:doi"
                      localAttribute: "doi"
                    - remoteAttribute: "dc:title"
                      localAttribute: "title"
                - name: DoctoralThesis
                  attributes:
                    - doi
                  mappers:
                    - remoteAttribute: "prism:doi"
                      localAttribute: "doi"
                    - remoteAttribute: "dc:title"
                      localAttribute: "title"
                - name: MasterThesis
                  attributes:
                    - doi
                  mappers:
                    - remoteAttribute: "prism:doi"
                      localAttribute: "doi"
                    - remoteAttribute: "dc:title"
                      localAttribute: "title"
                - name: Documento
                  attributes:
                    - doi
                  mappers:
                    - remoteAttribute: "prism:doi"
                      localAttribute: "doi"
                    - remoteAttribute: "dc:title"
                      localAttribute: "title"
            - remoteName: SCOPUS
              remoteAttribute: TITLE-ABS-KEY
              suffixURL: search/scopus
              identifier: false
              removeStopWords: true
              order: 2
              localClasses:
                - name: Article
                  attributes:
                    - title
                  mappers:
                    - remoteAttribute: "doi"
                      localAttribute: "doi"
                    - remoteAttribute: "dc:title"
                      localAttribute: "title"
                - name: Book
                  attributes:
                    - title
                  mappers:
                    - remoteAttribute: "prism:doi"
                      localAttribute: "doi"
                    - remoteAttribute: "dc:title"
                      localAttribute: "title"
                - name: BookChapter
                  attributes:
                    - title
                  mappers:
                    - remoteAttribute: "prism:doi"
                      localAttribute: "doi"
                    - remoteAttribute: "dc:title"
                      localAttribute: "title"
                - name: BookSection
                  attributes:
                    - title
                  mappers:
                    - remoteAttribute: "prism:doi"
                      localAttribute: "doi"
                    - remoteAttribute: "dc:title"
                      localAttribute: "title"
                - name: DoctoralThesis
                  attributes:
                    - title
                  mappers:
                    - remoteAttribute: "prism:doi"
                      localAttribute: "doi"
                    - remoteAttribute: "dc:title"
                      localAttribute: "title"
                - name: MasterThesis
                  attributes:
                    - title
                  mappers:
                    - remoteAttribute: "prism:doi"
                      localAttribute: "doi"
                    - remoteAttribute: "dc:title"
                      localAttribute: "title"
                - name: Documento
                  attributes:
                    - title
                  mapperAttribute:
                    - remoteAttribute: "doi"
                      localAttribute: "doi"
                    - remoteAttribute: "dc:title"
                      localAttribute: "title"
    - name: CROSSREF
      connections:
        - connectionType: API
          def: true
          baseURL: https://api.crossref.org/
          apiKey:
          mappings:
            - remoteName: WORKS
              remoteAttribute: works
              suffixURL: works/$var$
              identifier: true
              order: 1
              paramType: URI
              localClasses:
                - name: Article
                  attributes:
                    - doi
                  mappers:
                    - remoteAttribute: "DOI"
                      localAttribute: "doi"
                    - remoteAttribute: "title"
                      localAttribute: "title"
                - name: Book
                  attributes:
                    - doi
                  mappers:
                    - remoteAttribute: "DOI"
                      localAttribute: "doi"
                    - remoteAttribute: "title"
                      localAttribute: "title"
                - name: BookChapter
                  attributes:
                    - doi
                  mappers:
                    - remoteAttribute: "DOI"
                      localAttribute: "doi"
                    - remoteAttribute: "title"
                      localAttribute: "title"
                - name: BookSection
                  attributes:
                    - doi
                  mappers:
                    - remoteAttribute: "DOI"
                      localAttribute: "doi"
                    - remoteAttribute: "title"
                      localAttribute: "title"
                - name: DoctoralThesis
                  attributes:
                    - doi
                  mappers:
                    - remoteAttribute: "DOI"
                      localAttribute: "doi"
                    - remoteAttribute: "title"
                      localAttribute: "title"
                - name: MasterThesis
                  attributes:
                    - doi
                  mappers:
                    - remoteAttribute: "DOI"
                      localAttribute: "doi"
                    - remoteAttribute: "title"
                      localAttribute: "title"
                - name: Documento
                  attributes:
                    - doi
                  mappers:
                    - remoteAttribute: "DOI"
                      localAttribute: "doi"
                    - remoteAttribute: "title"
                      localAttribute: "title"
    - name: WIKIDATA
      connections:
        - connectionType: SPARQL
          def: true
          baseURL: https://query.wikidata.org/sparql
          apiKey:
          mappings:
            - remoteName: WIKIDATA
              remoteAttribute: "ORCID"
              suffixURL:
              query: SELECT%20%3Fcompany%20%3Fwd%20%3FwdLabel%20%3Fps_Label%20%7B%20%3Fcompany%20wdt%3AP496%20%22$ORCID$%22%20.%20%3Fcompany%20%3Fp%20%3Fstatement%20.%20%3Fstatement%20%3Fps%20%3Fps_%20.%20%3Fwd%20wikibase%3Aclaim%20%3Fp.%20%3Fwd%20wikibase%3AstatementProperty%20%3Fps.%20OPTIONAL%20%7B%20%3Fstatement%20%3Fpq%20%3Fpq_%20.%20%3Fwdpq%20wikibase%3Aqualifier%20%3Fpq%20.%20%7D%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20%7D%20%7D%20ORDER%20BY%20%3Fwd%20%3Fstatement%20%3Fps_
              identifier: true
              order: 1
              paramType: SPARQL
              localClasses:
                - name: Persona
                  attributes:
                    - ORCID
                  mappers:
                    - remoteAttribute: "wde:P496"
                      localAttribute: "ORCID"
    - name: ORCID
      connections:
        - connectionType: API
          def: true
          baseURL: https://pub.orcid.org/v3.0
          apiKey:
          mappings:
          - remoteName: ORCID
            remoteAttribute: "q"
            suffixURL: /expanded-search
            query:
            identifier: true
            order: 1
            paramType: SPARQL
            localClasses:
              - name: Person
                attributes:
                  - ORCID
                mappers:
                  - remoteAttribute: "mOrcid"
                    localAttribute: "ORCID"
          - remoteName: ORCID>
            remoteAttribute: "q"
            suffixURL: /expanded-search
            query:
            identifier: false
            order: 2
            paramType: SPARQL
            localClasses:
              - name: Person
                attributes:
                  - name
                  - firstName
                  - surname
                mappers:
                  - remoteAttribute: "mOrcid"
                    localAttribute: "ORCID"
                  - remoteAttribute: "mName"
                    localAttribute: "name"
                  - remoteAttribute: "mFirstName"
                    localAttribute: "firstName"
                  - remoteAttribute: "mSurname"
                    localAttribute: "surname"
    - name: DOAJ
      connections:
        - connectionType: API
          def: true
          baseURL: https://doaj.org/api/v2
          apiKey:
          mappings:
            - remoteName: DOAJ
              remoteAttribute: "title:$var$"
              suffixURL: /search/articles
              query:
              identifier: false
              order: 1
              paramType: URI
              localClasses:
                - name: Article
                  attributes:
                    - title
                  mappers:
                    - remoteAttribute: "title"
                      localAttribute: "title"
            - remoteName: DOAJ
              remoteAttribute: "bibjson.eissn:$var$"
              suffixURL: /search/journals
              query:
              identifier: true
              order: 2
              paramType: URI
              localClasses:
                - name: Journal
                  attributes:
                    - eissn
                  mappers:
                    - remoteAttribute: "eissn"
                      localAttribute: "eissn"
                - name: Magazine
                  attributes:
                    - eissn
                  mappers:
                    - remoteAttribute: "eissn"
                      localAttribute: "eissn"
    - name: PUBMED
      connections:
        - connectionType: API
          def: true
          baseURL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils
          apiKey: 17425bf8f4968d2b8498e99c4ec18ce9db09
          mappings:
            - remoteName: PUBMED
              remoteAttribute: "title"
              suffixURL: /esearch.fcgi
              query:
              identifier: false
              order: 1
              paramType: QUERY
              localClasses:
                - name: Article
                  attributes:
                    - title
                  mappers:
                    - remoteAttribute: "title"
                      localAttribute: "title"
    - name: DBLP
      connections:
        - connectionType: API
          def: true
          baseURL: https://dblp.org
          apiKey:
          mappings:
            - remoteName: DBLP
              remoteAttribute: "q"
              suffixURL: /search/author/api
              query:
              identifier: true
              order: 1
              paramType: SPARQL
              localClasses:
                - name: Person
                  attributes:
                    - name
                    - firstName
                    - surname
                  mappers:
                    - remoteAttribute: "name"
                      localAttribute: "name"
                    - remoteAttribute: "firstName"
                      localAttribute: "firstName"
                    - remoteAttribute: "surname"
                      localAttribute: "surname"